version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5
      
  rtmp:
    build: ./apps/rtmp
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  auth:
    build: ./apps/auth
    restart: always
    ports:
      - "8000:8000"
    container_name: auth_server
    environment:
      - PORT=8000
  
  comments-service:
    build: ./apps/comments-service
    restart: always
    ports:
      - "3007:3007"
    container_name: comments-service
    environment:
      - PORT=3007
