apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
  labels:
    app: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: ktarneva/youconcert-comments-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: MONGO_URL
              value: mongodb+srv://kikitarneva:Bvm2Ze7Gocin3NEF@cluster1.4tcnjjg.mongodb.net/youConcert

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: comments-service
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "comments-service"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: Utilization
          averageUtilization: 10

---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  selector:
    app: comment
