apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-deployment
  labels:
    app: rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp
  template:
    metadata:
      labels:
        app: rtmp
    spec:
      containers:
        - name: rtmp
          image: youconcert-rtmp:latest
          ports:
            - containerPort: 1935  
---
apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
spec:
  selector:
    app: rtmp
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
