apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  MONGO_DB_USER: a2lraXRhcm5ldmE=
  MONGO_DB_PASSWORD: QnZtMlplN0dvY2luM05FRg==
  RabbitMQ_USER: ZnZibm5ic2I=
  RabbitMQ_PASSWORD: Te-b67XCoOoLkO8vyGILAFnh7xzSMJP2
  RabbitMQ_URL: YW1xcHM6Ly9mdmJubmJzYjpUZS1iNjdYQ29Pb0xrTzh2eUdJTEFGbmg3eHpTTUpQMkBnb29zZS5ybXEyLmNsb3VkYW1xcC5jb20vZnZibm5ic2I=
